name: test standard
description: run unit tests on pykalman
inputs:
  python-version-identifier:
    description: python version to run tests
    required: true

runs:
  using: composite
  steps:
    - name: repository checkout step
      uses: actions/checkout@v4

    - name: update tracking reference step
      run: git remote set-branches origin master
      shell: bash

    - name: shallow clone update step
      run: git fetch --depth 1
      shell: bash

    - name: python environment step
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version-identifier }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      shell: bash

    - name: Install sktime and dependencies
      run: python3 -m pip install .[tests]
      shell: bash

    - name: Show available branches
      run: git branch -a
      shell: bash

    - name: unit test step
      run: >-
        python3
        -m pytest
        pykalman/tests/test_standard.py
      shell: bash
